"""added bytes size column to jobs

Revision ID: 77d6ef31e9da
Revises: 2129702a5ee8
Create Date: 2025-10-29 19:34:06.946999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77d6ef31e9da'
down_revision: Union[str, Sequence[str], None] = '2129702a5ee8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('input_size_bytes', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('output_size_bytes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'output_size_bytes')
    op.drop_column('jobs', 'input_size_bytes')
    # ### end Alembic commands ###
