"""user->job relationship

Revision ID: f6bfb48b04b3
Revises: 38a1d65429b7
Create Date: 2025-10-02 22:54:52.153601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6bfb48b04b3'
down_revision: Union[str, Sequence[str], None] = '38a1d65429b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('user_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'user_id')
    # ### end Alembic commands ###
