version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - "5672:5672"
      - "15672:15672"

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pixelforge
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - pixelforge_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build:
      context: ../api
    volumes:
      - ../storage:/app/storage
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/pixelforge
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - UPLOAD_DIR=/app/storage/upload
      - CONVERTED_DIR=/app/storage/converted
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  img-worker:
    build:
      context: ../img-worker
    volumes:
      - ../storage:/app/storage
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/pixelforge
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - UPLOAD_DIR=/app/storage/upload
      - CONVERTED_DIR=/app/storage/converted
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

volumes:
  pixelforge_data:

